services:
  nextjs:
    container_name: dotl-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres 

  postgres:
    image: postgres:latest
    container_name: dotl-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dotladmin 
      POSTGRES_PASSWORD: dotlpassword
      POSTGRES_DB: dotl

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data 
    environment:
      MINIO_ROOT_USER: guilherme
      MINIO_ROOT_PASSWORD: guilherme123
    command: server /data 
